### Getting all inventory 
GET http://localhost:3000/shop/shop:47XNU8SlyOk9xtptWXNy6/inventory




### Buying Product
POST http://localhost:3000/shop/shop:47XNU8SlyOk9xtptWXNy6/inventory/buy-product
Content-Type: application/json 

{
    "productId": "prod:V1StGXR8_Z5jdHi6B-myT",
    "supplierId": "splr:Q7mX2vL9kR4pT8nYc5HdW",
    "quantity": 2
}

### Selling Product
POST http://localhost:3000/shop/shop:47XNU8SlyOk9xtptWXNy6/inventory/sell-product
Content-Type: application/json

{
    "productId": "prod:V1StGXR8_Z5jdHi6B-myT",
    "quantity": 14
}

### Setting price
POST http://localhost:3000/shop/shop:47XNU8SlyOk9xtptWXNy6/inventory/set-price
Content-Type: application/json

{
    "productId": "prod:V1StGXR8_Z5jdHi6B-myT",
    "price": 65
}