### Create Shop
POST http://localhost:3000/shop
Content-Type: application/json

{
    "playerId": "plyr:jwGDIxrp0COFfi5bJJxsQ",
    "name": "test-shop456"
}

### Update Status
PUT http://localhost:3000/shop/status/shop:47XNU8SlyOk9xtptWXNy6
Content-Type: application/json

{
    "status": "CLOSED"
}

### Update name
PUT http://localhost:3000/shop/name/shop:47XNU8SlyOk9xtptWXNy6
Content-Type: application/json

{
    "name": "test-12331"
}



### Get Shop By Id
GET http://localhost:3000/shop/shop:47XNU8SlyOk9xtptWXNy6


### Testing an ID that doesn't work
GET http://localhost:3000/shop/shop:h5Uvdc9TQDYdBwanjkwFc

